import com.mysql.cj.conf.ConnectionUrlParser.Pair;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.IOException;
import java.net.URI;
import java.net.http.*;
import org.json.*;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author CHANDRA PRAKASH
 */
public class MainScreen extends javax.swing.JFrame {
    static int[] close=new int[100];
    static int[] low= new int[100];
    static int[] open = new int[100];
    static int[] high = new int[100];
    static ArrayList<String> symbols = new ArrayList<String>();
    static String username;
    static String watchlistnew;
    static ArrayList<String> watchlist = new ArrayList<String>();
    public MainScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        titlePanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        sidePanel = new javax.swing.JPanel();
        Home_button = new javax.swing.JButton();
        Watchlist_button = new javax.swing.JButton();
        Logout_button = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        search_textField = new javax.swing.JTextField();
        SearchButton = new javax.swing.JButton();
        search_result_panel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        watchlist_panel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        graph1 = new Graph();
        jPanel5 = new javax.swing.JPanel();
        candlesticks2 = new Candlesticks();
        AddToWatchlist_button = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 94, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 98, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titlePanel.setBackground(new java.awt.Color(255, 51, 51));
        titlePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51), 2));
        titlePanel.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("TradeDeck");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Welcome to TradeVerse");

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addContainerGap(127, Short.MAX_VALUE)
                .addGroup(titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titlePanelLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(123, 123, 123))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titlePanelLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(228, 228, 228))))
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        getContentPane().add(titlePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, -5, 520, 100));

        sidePanel.setBackground(new java.awt.Color(255, 255, 255));
        sidePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51), 2));

        Home_button.setBackground(new java.awt.Color(255, 51, 51));
        Home_button.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Home_button.setForeground(new java.awt.Color(255, 255, 255));
        Home_button.setText("Home");
        Home_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Home_buttonActionPerformed(evt);
            }
        });

        Watchlist_button.setBackground(new java.awt.Color(255, 51, 51));
        Watchlist_button.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Watchlist_button.setForeground(new java.awt.Color(255, 255, 255));
        Watchlist_button.setText("Watchlist");
        Watchlist_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Watchlist_buttonActionPerformed(evt);
            }
        });

        Logout_button.setBackground(new java.awt.Color(255, 51, 51));
        Logout_button.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Logout_button.setForeground(new java.awt.Color(255, 255, 255));
        Logout_button.setText("Logout");
        Logout_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Logout_buttonActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/icon.jpeg"))); // NOI18N
        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Logout_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Watchlist_button, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                    .addComponent(Home_button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Home_button, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Watchlist_button, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Logout_button, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(177, 177, 177))
        );

        getContentPane().add(sidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 510));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        search_textField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 2));

        SearchButton.setBackground(new java.awt.Color(0, 153, 255));
        SearchButton.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        SearchButton.setForeground(new java.awt.Color(255, 255, 255));
        SearchButton.setText("Search");
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });

        search_result_panel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout search_result_panelLayout = new javax.swing.GroupLayout(search_result_panel);
        search_result_panel.setLayout(search_result_panelLayout);
        search_result_panelLayout.setHorizontalGroup(
            search_result_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 478, Short.MAX_VALUE)
        );
        search_result_panelLayout.setVerticalGroup(
            search_result_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 292, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(search_result_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(search_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SearchButton)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(search_textField)
                    .addComponent(SearchButton, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(search_result_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab1", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        watchlist_panel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout watchlist_panelLayout = new javax.swing.GroupLayout(watchlist_panel);
        watchlist_panel.setLayout(watchlist_panelLayout);
        watchlist_panelLayout.setHorizontalGroup(
            watchlist_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 484, Short.MAX_VALUE)
        );
        watchlist_panelLayout.setVerticalGroup(
            watchlist_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 391, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(watchlist_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 126, Short.MAX_VALUE)
                .addComponent(watchlist_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("tab2", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane2.setBackground(new java.awt.Color(255, 255, 255));

        graph1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout graph1Layout = new javax.swing.GroupLayout(graph1);
        graph1.setLayout(graph1Layout);
        graph1Layout.setHorizontalGroup(
            graph1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 504, Short.MAX_VALUE)
        );
        graph1Layout.setVerticalGroup(
            graph1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 316, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(graph1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(graph1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("raw", jPanel4);

        candlesticks2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout candlesticks2Layout = new javax.swing.GroupLayout(candlesticks2);
        candlesticks2.setLayout(candlesticks2Layout);
        candlesticks2Layout.setHorizontalGroup(
            candlesticks2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 479, Short.MAX_VALUE)
        );
        candlesticks2Layout.setVerticalGroup(
            candlesticks2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 317, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(candlesticks2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(candlesticks2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("candlestick", jPanel5);

        AddToWatchlist_button.setBackground(new java.awt.Color(255, 0, 0));
        AddToWatchlist_button.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        AddToWatchlist_button.setForeground(new java.awt.Color(255, 255, 255));
        AddToWatchlist_button.setText("Add to Watchlist");
        AddToWatchlist_button.setBorder(null);
        AddToWatchlist_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddToWatchlist_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(AddToWatchlist_button, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 135, Short.MAX_VALUE)
                .addComponent(AddToWatchlist_button, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("tab3", jPanel3);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, -42, 520, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Home_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Home_buttonActionPerformed
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_Home_buttonActionPerformed

    private void Watchlist_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Watchlist_buttonActionPerformed
        try {
            // TODO add your handling code here:
            getwatchlist();
            ArrayList<Pair<javax.swing.JButton,javax.swing.JButton>> wlbuttons = new ArrayList<Pair<javax.swing.JButton,javax.swing.JButton>>();
            for(int i=0;i<watchlist.size();i++){
                javax.swing.JButton wlbutton = new javax.swing.JButton(watchlist.get(i));
                wlbutton.setBounds(50,50+i*30,200,30);
                wlbutton.setBackground(Color.pink);
                
                javax.swing.JButton dbutton = new javax.swing.JButton("X");
                dbutton.setBounds(260,50+i*30,40,30);
                dbutton.setForeground(Color.white);
                dbutton.setBackground(Color.red);
                
                String symbol = watchlist.get(i);
                //System.out.println(watchlist.get(i));
                wlbutton.addMouseListener(new MouseAdapter(){
                    public void mousePressed(MouseEvent me){
                        try {
                            fetch(symbol);
                            graph1.cordy=close;
                            candlesticks2.low=low;
                            candlesticks2.high=high;
                            candlesticks2.open=open;
                            candlesticks2.close=close;
                            watchlistnew=symbol;
                            jTabbedPane1.setSelectedIndex(2);
                        } catch (IOException ex) {
                            Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (InterruptedException ex) {
                            Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                });
                dbutton.addMouseListener(new MouseAdapter(){
                    public void mousePressed(MouseEvent me){
                        try {
                            deletefromwatchlist(symbol);
                        } catch (ClassNotFoundException ex) {
                            Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (SQLException ex) {
                            Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                });
                wlbuttons.add(new Pair<javax.swing.JButton,javax.swing.JButton>(wlbutton,dbutton));
            }
            watchlist_panel.removeAll();
            for(int i=0;i<wlbuttons.size();i++){
                Pair<javax.swing.JButton,javax.swing.JButton> ans = wlbuttons.get(i);
                watchlist_panel.add(ans.left);
                watchlist_panel.add(ans.right);
                watchlist_panel.repaint();
                watchlist_panel.validate();
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_Watchlist_buttonActionPerformed

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        // TODO add your handling code here:
        String keyword = search_textField.getText();
        try {
            search(keyword);
            ArrayList<javax.swing.JButton> stockbuttons = new ArrayList<javax.swing.JButton>();
            for(int i=0;i<symbols.size();i++){
                javax.swing.JButton stocks = new javax.swing.JButton(symbols.get(i));
                stocks.setBounds(50,50+i*30,200,30);
                stocks.setBackground(Color.pink);
            
                String symbol = symbols.get(i);
                stocks.addMouseListener(new MouseAdapter(){
                    public void mousePressed(MouseEvent me){
                        try {
                            fetch(symbol);
                            graph1.cordy=close;
                            candlesticks2.low=low;
                            candlesticks2.high=high;
                            candlesticks2.open=open;
                            candlesticks2.close=close;
                            watchlistnew=symbol;
                            jTabbedPane1.setSelectedIndex(2);
                        } catch (IOException ex) {
                            Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (InterruptedException ex) {
                            Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                });
                stockbuttons.add(stocks);
            }
            search_result_panel.removeAll();
            for(int i=0;i<stockbuttons.size();i++){
                search_result_panel.add(stockbuttons.get(i));
                search_result_panel.repaint();
                search_result_panel.validate();
            }
        } catch (IOException ex) {
            Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void Logout_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Logout_buttonActionPerformed
        // TODO add your handling code here:
        LoginPage lp = new LoginPage();
        lp.setVisible(true);
        lp.pack();
        lp.setLocationRelativeTo(null);
        lp.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_Logout_buttonActionPerformed

    private void AddToWatchlist_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddToWatchlist_buttonActionPerformed
        try {
            // TODO add your handling code here:
            if(watchlist.contains(watchlistnew)){
                JOptionPane.showMessageDialog(null, "Already in watchlist");
            }else{
                addtowatchlist(watchlistnew);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_AddToWatchlist_buttonActionPerformed
    
    public static void getwatchlist() throws ClassNotFoundException, SQLException{
        watchlist.clear();
        PreparedStatement ps;
        ResultSet rs;
        String query ="SELECT * FROM WATCHLIST WHERE USERNAME='"+username+"';";
        ps=SqlConnection.getConnection().prepareStatement(query);
        rs = ps.executeQuery();
        while(rs.next()){
            watchlist.add(rs.getString("stocks"));
        }
    }
    
    //search
    public static void search(String keyword) throws IOException, InterruptedException{
         symbols.clear();
        String url = "https://www.alphavantage.co/query?function=SYMBOL_SEARCH&keywords="+keyword+"&apikey=JRKA4B1LDJ4MDRW7";
        
        HttpRequest request = HttpRequest.newBuilder().GET().uri(URI.create(url)).build();
        HttpClient client = HttpClient.newBuilder().build();
        HttpResponse <String> response = client.send(request,HttpResponse.BodyHandlers.ofString());
        
        String info = response.body();
        //System.out.println("response : "+info);
        
        JSONObject obj = new JSONObject(info);
        JSONArray bestmatches = obj.getJSONArray("bestMatches");
        for(int i=0;i<bestmatches.length();i++){
            JSONObject results = bestmatches.getJSONObject(i);
            String symbol = results.getString("1. symbol");
            symbols.add(symbol);
        }    
        //System.out.println("stocks"+symbols.toString());
     }


    public static void addtowatchlist(String stock) throws ClassNotFoundException, SQLException{
        PreparedStatement ps;
        String query = "INSERT INTO WATCHLIST VALUES('"+username+"','"+stock+"');";
        ps=SqlConnection.getConnection().prepareStatement(query);
        if(ps.executeUpdate()>0){
            JOptionPane.showMessageDialog(null, "Added to Watchlist");
        }            
    }
    
    public void deletefromwatchlist(String stock) throws ClassNotFoundException, SQLException{
        PreparedStatement ps;
        String query = "DELETE FROM WATCHLIST WHERE USERNAME='"+username+"' AND STOCKS='"+stock+"';";
        ps=SqlConnection.getConnection().prepareStatement(query);
        if(ps.executeUpdate()>0){
            JOptionPane.showMessageDialog(null, "Successfully deleted from Watchlist");
            MainScreen ms = new MainScreen();
            ms.setVisible(true);
            ms.pack();
            ms.setLocationRelativeTo(null);
            ms.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
        } 
    }

    //fetch data
    public static void fetch(String keyword) throws IOException, InterruptedException{
        String url = "https://www.alphavantage.co/query?function=TIME_SERIES_DAILY_ADJUSTED&symbol="+keyword+"&apikey=JRKA4B1LDJ4MDRW7";
        
        HttpRequest request = HttpRequest.newBuilder().GET().uri(URI.create(url)).build();
        HttpClient client = HttpClient.newBuilder().build();
        HttpResponse <String> response = client.send(request,HttpResponse.BodyHandlers.ofString());
//        System.out.println(response.body());
        
        String info = response.body();
        
        JSONObject obj = new JSONObject(info);
        //System.out.println("obj : "+obj);
        JSONObject time = obj.getJSONObject("Time Series (Daily)");
        //System.out.println("time : "+time);
        
        Set<String> keys = time.keySet();
        String[] dates = keys.toArray(new String[keys.size()]);
        
        Arrays.sort(dates);
        //System.out.println("dates : "+Arrays.toString(dates));
       
        for(int i=0;i<dates.length;i++){
            close[i]=(int)Double.parseDouble(time.getJSONObject(dates[i]).getString("4. close"));
            open[i]=(int)Double.parseDouble(time.getJSONObject(dates[i]).getString("1. open"));
            low[i]=(int)Double.parseDouble(time.getJSONObject(dates[i]).getString("3. low"));
            high[i]=(int)Double.parseDouble(time.getJSONObject(dates[i]).getString("2. high"));
        }            
        //System.out.println("closing values : "+Arrays.toString(close));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException, InterruptedException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        fetch("MSFT");
//        search("amazon");
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddToWatchlist_button;
    private javax.swing.JButton Home_button;
    private javax.swing.JButton Logout_button;
    private javax.swing.JButton SearchButton;
    private javax.swing.JButton Watchlist_button;
    private Candlesticks candlesticks2;
    private Graph graph1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JPanel search_result_panel;
    private javax.swing.JTextField search_textField;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JPanel watchlist_panel;
    // End of variables declaration//GEN-END:variables
}
