
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author sumit
 */
public class login_page extends javax.swing.JFrame {

    /**
     * Creates new form login_page
     */
    public login_page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        loginpage = new javax.swing.JPanel();
        loginpage_leftcontainer = new javax.swing.JPanel();
        leftcontainer_img = new javax.swing.JLabel();
        leftcontainer_txt = new javax.swing.JTextField();
        loginpage_companyname = new javax.swing.JLabel();
        login_detail_container = new javax.swing.JPanel();
        Login_heading = new javax.swing.JLabel();
        login_username = new javax.swing.JLabel();
        username_input = new javax.swing.JTextField();
        login_password = new javax.swing.JLabel();
        password_input = new javax.swing.JPasswordField();
        login_submit = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        loginpage.setBackground(new java.awt.Color(255, 102, 102));

        loginpage_leftcontainer.setBackground(new java.awt.Color(204, 204, 255));

        leftcontainer_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/img.containerL.jpg"))); // NOI18N

        leftcontainer_txt.setBackground(new java.awt.Color(84, 153, 221));
        leftcontainer_txt.setFont(new java.awt.Font("Script MT Bold", 0, 25)); // NOI18N
        leftcontainer_txt.setText("Simple, Free Investing");
        leftcontainer_txt.setBorder(null);
        leftcontainer_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftcontainer_txtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginpage_leftcontainerLayout = new javax.swing.GroupLayout(loginpage_leftcontainer);
        loginpage_leftcontainer.setLayout(loginpage_leftcontainerLayout);
        loginpage_leftcontainerLayout.setHorizontalGroup(
            loginpage_leftcontainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginpage_leftcontainerLayout.createSequentialGroup()
                .addComponent(leftcontainer_img)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(loginpage_leftcontainerLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(leftcontainer_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        loginpage_leftcontainerLayout.setVerticalGroup(
            loginpage_leftcontainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginpage_leftcontainerLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(leftcontainer_img, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(leftcontainer_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        loginpage_companyname.setFont(new java.awt.Font("Segoe UI Emoji", 0, 48)); // NOI18N
        loginpage_companyname.setForeground(new java.awt.Color(253, 250, 156));
        loginpage_companyname.setText("Indious");

        login_detail_container.setBackground(new java.awt.Color(231, 216, 194));

        Login_heading.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        Login_heading.setForeground(new java.awt.Color(102, 102, 102));
        Login_heading.setText("Login");

        login_username.setFont(new java.awt.Font("Segoe UI Emoji", 0, 16)); // NOI18N
        login_username.setText("Username:");

        username_input.setToolTipText("Enter your Username");

        login_password.setFont(new java.awt.Font("Segoe UI Emoji", 0, 16)); // NOI18N
        login_password.setText("Password:");

        password_input.setToolTipText("Enter your Password");

        login_submit.setBackground(new java.awt.Color(255, 153, 51));
        login_submit.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        login_submit.setForeground(new java.awt.Color(255, 255, 255));
        login_submit.setText("Submit");
        login_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_submitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout login_detail_containerLayout = new javax.swing.GroupLayout(login_detail_container);
        login_detail_container.setLayout(login_detail_containerLayout);
        login_detail_containerLayout.setHorizontalGroup(
            login_detail_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, login_detail_containerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Login_heading, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126))
            .addGroup(login_detail_containerLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(login_detail_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(login_username)
                    .addComponent(login_password))
                .addGap(18, 18, 18)
                .addGroup(login_detail_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(username_input)
                    .addComponent(password_input, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                    .addGroup(login_detail_containerLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(login_submit, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        login_detail_containerLayout.setVerticalGroup(
            login_detail_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(login_detail_containerLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(Login_heading)
                .addGap(46, 46, 46)
                .addGroup(login_detail_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(login_username)
                    .addComponent(username_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(login_detail_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(login_password)
                    .addComponent(password_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(login_submit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout loginpageLayout = new javax.swing.GroupLayout(loginpage);
        loginpage.setLayout(loginpageLayout);
        loginpageLayout.setHorizontalGroup(
            loginpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginpageLayout.createSequentialGroup()
                .addComponent(loginpage_leftcontainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addGroup(loginpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginpageLayout.createSequentialGroup()
                        .addComponent(login_detail_container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginpageLayout.createSequentialGroup()
                        .addComponent(loginpage_companyname, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(179, 179, 179))))
        );
        loginpageLayout.setVerticalGroup(
            loginpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginpageLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(loginpage_companyname, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(login_detail_container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
            .addComponent(loginpage_leftcontainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loginpage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loginpage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void leftcontainer_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftcontainer_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_leftcontainer_txtActionPerformed

    private void login_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_submitActionPerformed
        String Username = username_input.getText();
        String Password = String.valueOf(password_input.getPassword());
                    if(Username.isBlank()){
               JOptionPane.showMessageDialog(null, "Username Cannot be blank");
            }
               else if(Password.isBlank()){
                   JOptionPane.showMessageDialog(null, "Password Cannot be blank");
               }
               else{
        System.out.println( "Username is " +Username);
        System.out.println( "Password is " +Password);}
    }//GEN-LAST:event_login_submitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Login_heading;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel leftcontainer_img;
    private javax.swing.JTextField leftcontainer_txt;
    private javax.swing.JPanel login_detail_container;
    private javax.swing.JLabel login_password;
    private javax.swing.JButton login_submit;
    private javax.swing.JLabel login_username;
    private javax.swing.JPanel loginpage;
    private javax.swing.JLabel loginpage_companyname;
    private javax.swing.JPanel loginpage_leftcontainer;
    private javax.swing.JPasswordField password_input;
    private javax.swing.JTextField username_input;
    // End of variables declaration//GEN-END:variables
}
