
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.IOException;
import java.net.URI;
import java.util.*;
import java.net.http.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.json.*;







/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author sumit
 */
public class mainpage extends javax.swing.JFrame {
       static int[] close= new int[100];
       static int[] open= new int[100];
       static int[] high= new int[100];
       static int[] low= new int[100];
       static ArrayList<String> symbols= new ArrayList<String>();
    /**
     * Creates new form mainpage
     */
    public mainpage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainpage_titlecontainer = new javax.swing.JPanel();
        bckimg_mainpage = new javax.swing.JLabel();
        titleheading_mainpage = new javax.swing.JLabel();
        mainpage_leftcontainer = new javax.swing.JPanel();
        Home_button = new javax.swing.JButton();
        watchlist_button = new javax.swing.JButton();
        logout_button = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        Search_feild = new javax.swing.JTextField();
        Search_button = new javax.swing.JButton();
        serch_result_pannel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        graph_section = new javax.swing.JTabbedPane();
        raw_graph = new javax.swing.JPanel();
        graph2 = new Graph();
        candlestick_graph = new javax.swing.JPanel();
        candlestick_graph2 = new candlestick_graph();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainpage_titlecontainer.setBackground(new java.awt.Color(255, 153, 153));

        bckimg_mainpage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/topimg.jpg"))); // NOI18N

        titleheading_mainpage.setFont(new java.awt.Font("Segoe UI Variable", 0, 55)); // NOI18N
        titleheading_mainpage.setText("Indious");

        javax.swing.GroupLayout mainpage_titlecontainerLayout = new javax.swing.GroupLayout(mainpage_titlecontainer);
        mainpage_titlecontainer.setLayout(mainpage_titlecontainerLayout);
        mainpage_titlecontainerLayout.setHorizontalGroup(
            mainpage_titlecontainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainpage_titlecontainerLayout.createSequentialGroup()
                .addComponent(bckimg_mainpage, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(186, 186, 186)
                .addComponent(titleheading_mainpage, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 328, Short.MAX_VALUE))
        );
        mainpage_titlecontainerLayout.setVerticalGroup(
            mainpage_titlecontainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bckimg_mainpage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mainpage_titlecontainerLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(titleheading_mainpage, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(mainpage_titlecontainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 891, 130));

        mainpage_leftcontainer.setBackground(new java.awt.Color(32, 93, 165));

        Home_button.setBackground(new java.awt.Color(204, 204, 204));
        Home_button.setText("Home");
        Home_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Home_buttonActionPerformed(evt);
            }
        });

        watchlist_button.setBackground(new java.awt.Color(204, 204, 204));
        watchlist_button.setText("Watchlist");
        watchlist_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                watchlist_buttonActionPerformed(evt);
            }
        });

        logout_button.setBackground(new java.awt.Color(204, 204, 204));
        logout_button.setText("Logout");
        logout_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainpage_leftcontainerLayout = new javax.swing.GroupLayout(mainpage_leftcontainer);
        mainpage_leftcontainer.setLayout(mainpage_leftcontainerLayout);
        mainpage_leftcontainerLayout.setHorizontalGroup(
            mainpage_leftcontainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainpage_leftcontainerLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(mainpage_leftcontainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logout_button, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(watchlist_button, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Home_button, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        mainpage_leftcontainerLayout.setVerticalGroup(
            mainpage_leftcontainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainpage_leftcontainerLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(Home_button, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(watchlist_button, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logout_button, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(255, Short.MAX_VALUE))
        );

        getContentPane().add(mainpage_leftcontainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 160, 430));

        Search_feild.setToolTipText("Search Stocks Here");

        Search_button.setText("Search");
        Search_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout serch_result_pannelLayout = new javax.swing.GroupLayout(serch_result_pannel);
        serch_result_pannel.setLayout(serch_result_pannelLayout);
        serch_result_pannelLayout.setHorizontalGroup(
            serch_result_pannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 441, Short.MAX_VALUE)
        );
        serch_result_pannelLayout.setVerticalGroup(
            serch_result_pannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(serch_result_pannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Search_feild, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Search_button, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(252, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Search_feild, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Search_button, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(serch_result_pannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("tab1", jPanel1);

        jLabel2.setText("tab2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(402, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(349, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(254, 254, 254))
        );

        jTabbedPane2.addTab("tab2", jPanel2);

        javax.swing.GroupLayout graph2Layout = new javax.swing.GroupLayout(graph2);
        graph2.setLayout(graph2Layout);
        graph2Layout.setHorizontalGroup(
            graph2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 445, Short.MAX_VALUE)
        );
        graph2Layout.setVerticalGroup(
            graph2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 342, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout raw_graphLayout = new javax.swing.GroupLayout(raw_graph);
        raw_graph.setLayout(raw_graphLayout);
        raw_graphLayout.setHorizontalGroup(
            raw_graphLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(raw_graphLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(graph2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        raw_graphLayout.setVerticalGroup(
            raw_graphLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(raw_graphLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(graph2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        graph_section.addTab("Raw", raw_graph);

        javax.swing.GroupLayout candlestick_graph2Layout = new javax.swing.GroupLayout(candlestick_graph2);
        candlestick_graph2.setLayout(candlestick_graph2Layout);
        candlestick_graph2Layout.setHorizontalGroup(
            candlestick_graph2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 551, Short.MAX_VALUE)
        );
        candlestick_graph2Layout.setVerticalGroup(
            candlestick_graph2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 321, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout candlestick_graphLayout = new javax.swing.GroupLayout(candlestick_graph);
        candlestick_graph.setLayout(candlestick_graphLayout);
        candlestick_graphLayout.setHorizontalGroup(
            candlestick_graphLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 681, Short.MAX_VALUE)
            .addGroup(candlestick_graphLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, candlestick_graphLayout.createSequentialGroup()
                    .addContainerGap(75, Short.MAX_VALUE)
                    .addComponent(candlestick_graph2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(55, Short.MAX_VALUE)))
        );
        candlestick_graphLayout.setVerticalGroup(
            candlestick_graphLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 333, Short.MAX_VALUE)
            .addGroup(candlestick_graphLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(candlestick_graphLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(candlestick_graph2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        graph_section.addTab("Candlestick", candlestick_graph);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(graph_section, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(249, Short.MAX_VALUE)
                .addComponent(graph_section, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("tab3", jPanel3);

        getContentPane().add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, -140, 600, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Home_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Home_buttonActionPerformed
        // TODO add your handling code here:
        jTabbedPane2.setSelectedIndex(0);
        
    }//GEN-LAST:event_Home_buttonActionPerformed

    private void watchlist_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_watchlist_buttonActionPerformed
        // TODO add your handling code here:
        jTabbedPane2.setSelectedIndex(1);
    }//GEN-LAST:event_watchlist_buttonActionPerformed

    private void logout_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_buttonActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_logout_buttonActionPerformed

    private void Search_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_buttonActionPerformed
        // TODO add your handling code here:
        String keyword=Search_feild.getText();
           try {
               search(keyword);
               ArrayList<javax.swing.JButton> stockbuttons= new ArrayList<javax.swing.JButton>();
               
               for(int i=0;i<symbols.size();i++){
                   javax.swing.JButton stock= new javax.swing.JButton(symbols.get(i));
                   stock.setBounds(50, 50+i*30, 150, 30);
                   String symbol= symbols.get(i);
                   stock.addMouseListener(new MouseAdapter(){
                      public void mousePressed(MouseEvent me){
                          try {
                              fetch(symbol);
                              graph2.cordy= close;
                              candlestick_graph2.close=close;
                              candlestick_graph2.high=high;
                              candlestick_graph2.low=low;
                              candlestick_graph2.open=open;
                              jTabbedPane2.setSelectedIndex(2);
                              
                              
                          } catch (IOException ex) {
                              Logger.getLogger(mainpage.class.getName()).log(Level.SEVERE, null, ex);
                          } catch (InterruptedException ex) {
                              Logger.getLogger(mainpage.class.getName()).log(Level.SEVERE, null, ex);
                          }
                          
                      }
                   
                   
                   });
                   
                   stockbuttons.add(stock);
               }
               
               serch_result_pannel.removeAll();
               for(int i=0;i<stockbuttons.size();i++){
                   serch_result_pannel.add(stockbuttons.get(i));
                   serch_result_pannel.repaint();
                   serch_result_pannel.validate();
               }
               
               
           } catch (IOException ex) {
               Logger.getLogger(mainpage.class.getName()).log(Level.SEVERE, null, ex);
           } catch (InterruptedException ex) {
               Logger.getLogger(mainpage.class.getName()).log(Level.SEVERE, null, ex);
           }
    }//GEN-LAST:event_Search_buttonActionPerformed
     
    //search
    public static void search(String keyword) throws IOException, InterruptedException{
        symbols.clear();
        String url="https://www.alphavantage.co/query?function=SYMBOL_SEARCH&keywords="+keyword+"&apikey=0IRM8U5QVUZF4ATU";
        
         HttpRequest request= HttpRequest.newBuilder().GET().uri(URI.create(url)).build();
         HttpClient client= HttpClient.newBuilder().build();
         HttpResponse <String> response= client.send(request, HttpResponse.BodyHandlers.ofString());
         String info= response.body();
//         System.out.println("response" +info);
         
         JSONObject obj= new JSONObject(info);
         JSONArray bestmatches = obj.getJSONArray("bestMatches");
         
         for(int i=0;i<bestmatches.length();i++){
             JSONObject result= bestmatches.getJSONObject(i);
             String symbol = result.getString("1. symbol");
             symbols.add(symbol);
         }
            System.out.println("stocks:" +symbols.toString());
    }
    
    
    
    
    //fetch data
    public static void fetch(String keyword) throws IOException, InterruptedException{
        String url="https://www.alphavantage.co/query?function=TIME_SERIES_DAILY_ADJUSTED&symbol="+keyword+"&apikey=0IRM8U5QVUZF4ATU";
        
         HttpRequest request= HttpRequest.newBuilder().GET().uri(URI.create(url)).build();
         HttpClient client= HttpClient.newBuilder().build();
         HttpResponse <String> response= client.send(request, HttpResponse.BodyHandlers.ofString());
         String info= response.body();
         
         JSONObject obj= new JSONObject(info); 
//         System.out.println("obj:" +obj);
         JSONObject time= obj.getJSONObject("Time Series (Daily)");
//        System.out.print("time:" + time);
         
         
         //storing all the dates
         
         Set<String> keys= time.keySet();
         String[] dates= keys.toArray(new String[keys.size()]);
         
         Arrays.sort(dates);
//         System.out.println("dates:" +Arrays.toString(dates));
         
         
         for(int i=0;i<dates.length;i++){
             close[i]=(int)Double.parseDouble(time.getJSONObject(dates[i]).getString("4. close"));
             open[i]=(int) Double.parseDouble(time.getJSONObject(dates[i]).getString("1. open"));
              high[i]=(int) Double.parseDouble(time.getJSONObject(dates[i]).getString("2. high"));
              low[i]=(int) Double.parseDouble(time.getJSONObject(dates[i]).getString("3. low"));
         }
//         System.out.println("closing values" +Arrays.toString(close));
         
         
         
       
         
         
    }   
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException, InterruptedException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
          
          //      fetch("MSFT");
      search("amazon");
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
   

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainpage().setVisible(true);
            }
        });
    }

    
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Home_button;
    private javax.swing.JButton Search_button;
    private javax.swing.JTextField Search_feild;
    private javax.swing.JLabel bckimg_mainpage;
    private javax.swing.JPanel candlestick_graph;
    private candlestick_graph candlestick_graph2;
    private Graph graph2;
    private javax.swing.JTabbedPane graph_section;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JButton logout_button;
    private javax.swing.JPanel mainpage_leftcontainer;
    private javax.swing.JPanel mainpage_titlecontainer;
    private javax.swing.JPanel raw_graph;
    private javax.swing.JPanel serch_result_pannel;
    private javax.swing.JLabel titleheading_mainpage;
    private javax.swing.JButton watchlist_button;
    // End of variables declaration//GEN-END:variables
}
